### ISSUE TITLE
Where is the main game file?

### ISSUE THREAD

**Issue by probonopd** [CosmicCitadel/StarSpaceDiamond#1]
After compiling, I get `starspacediamond-test-library`. Is this the main game?

Build log:
https://api.travis-ci.com/v3/job/194590686/log.txt

**Comment by CosmicCitadel** [comment]
The main game file is app.d.  The project is managed by the dub package manager, so to build the project you just go into the main directory and run "dub build" to compile the project, or "dub run" to compile and then run the project.

**Comment by probonopd** [comment]
> The main game file is app.d. 

I don't seem to have `app.d` - am I doing something wrong?

https://api.travis-ci.com/v3/job/194590686/log.txt

Here is my Travis CI build script:
https://github.com/probonopd/StarSpaceDiamond/blob/patch-1/.travis.yml

Yes, but is there a [desktop file](https://standards.freedesktop.org/desktop-entry-spec/latest/) so that I can open the resulting application from the menu following `make install`?

**Comment by CosmicCitadel** [comment]
Right now the game is still being developed so there's no package of it or .desktop file at the moment.

First, make sure you've downloaded and installed the DMD compiler, as it should come with the dub package manager.  Then either download a zip of the code or use git to get it, and put everything in its own directory.  Using the command line, go into that directory and run "dub build".  It should automatically download all the .d dependencies you need, though you'll also need to install the libSDL2 libraries at the moment.  Once the build completes successfully, you should have a starspacediamond file available in the current directory which you can run, or you can use the "dub run" command from within that directory.

From looking at your log files I see you're using Ubuntu 14.04.  This is being developed on Ubuntu 19.04.  It also looks like you're perhaps trying to use more steps than you need to.  Make sure you go to http://www.dlang.org and download the latest DMD package and install that, then simply retrieve the source code and use dub from the command line yourself as described above.  There's no need to use Travis or other tools.  That just adds more complexity than is really required at this point.

**Comment by probonopd** [comment]
Getting somewhere... thanks to your explanations and some trial and error I was able to compile it. 👍 

I am trying to bundle it as an [AppImage](http://appimage.org/), and interestingly the required dynamic libraries seem not to be recognized by `ldd`.

https://github.com/AppImage/appimage.github.io/pull/1494

Do you happen to know whether D tries to load libraries using `dlopen()`?

**Comment by probonopd** [comment]
I was able to compile an AppImage. After inserting the missing library dependencies using patchelf the were bundled by linuxdeployqt correctly and I can now launch the resulting AppImage. However, it crashes then:

```
LSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4292:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4771:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2266:(snd_pcm_open_noupdate) Unknown PCM default
core.exception.AssertError@../../../.dub/packages/dgame-0.6.6/dgame/source/Dgame/Internal/Error.d(36): Warning: Could not open Mix_OpenAudio: ALSA: Couldn't open audio d
----------------
??:? _d_assert_msg [0x4ffeae]
../../../.dub/packages/dgame-0.6.6/dgame/source/Dgame/Internal/Error.d:36 nothrow @nogc void Dgame.Internal.Error.assert_fmt!(const(char)*).assert_fmt(bool, immutable(char)[], const(char)*) [0x4c8cf4]
../../../.dub/packages/dgame-0.6.6/dgame/source/Dgame/Window/Internal/Init.d:119 void Dgame.Window.Internal.Init._initSDL() [0x4d1324]
../../../.dub/packages/dgame-0.6.6/dgame/source/Dgame/Window/Window.d:141 ref Dgame.Window.Window.Window Dgame.Window.Window.Window.__ctor(const(Dgame.Math.Rect.Rect), immutable(char)[], uint, const(Dgame.Window.GLContextSettings.GLContextSettings)) [0x4ccd16]
../../../.dub/packages/dgame-0.6.6/dgame/source/Dgame/Window/Window.d:121 ref Dgame.Window.Window.Window Dgame.Window.Window.Window.__ctor(uint, uint, immutable(char)[], uint, const(Dgame.Window.GLContextSettings.GLContextSettings)) [0x4ccc22]
source/app.d:7 _Dmain [0x4c56ec]
SDL version: 2.0.2
Warning: No mp3 support: Mixer not built with MP3 support

NUMBER_OF_WINDOWS: 0
ERROR: Could not find a single window on screen :-(
```

Do you have an idea why it does not show a window on the (X11) screen?

**Comment by CosmicCitadel** [comment]
It looks like it's not able to initialize SDL, perhaps related to the audio errors.  As long as all the proper SDL libraries are included in the package and LD_LIBRARY_PATH is set properly it should work, although maybe there's some sort of version issue going on.
